[Settings]
  ID = "928059cc-4f46-4b8a-9d89-d2c58dfe6d4f"

[build]
  command = "npm run build"
  functions = "lambda"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200